### PR TITLE
Added mkdir to each build step

### PR DESCRIPTION
**Pull request by btetz14**
Making the project on Windows using the Bash Shell works.  However, you have to issue the make command twice or pre-make the "_build" directory.
By adding the mkdir command to each step, the make command works fine the first try.
This change should not impact making under Linux or slow down the build process.

### CODE REVIEW

**Comment by nealjack** [comment]
Hey Brian, thanks for the pull request.

Could you tell me what your steps were to install make + arm-none-eabi-gcc for git bash (MINGW64)? I'm trying to replicate your setup.

**Comment by btetz14** [comment]
make
   http://gnuwin32.sourceforge.net/packages/make.htm
   Download "Complete package, except sources" "Setup" "3384653" "25 November 2006"
   Install make-3.81.exe
   make.exe will be installed to C:\Program Files (x86)\GnuWin32\bin
   Open "Edit the system Environment Variables" and click "Environment Variables"
   Edit the "System Variable" "path"
   Add "C:\Program Files (x86)\GnuWin32\bin"
   Now you can use "make" in any shell.  If it doesn't work enter "refreshenv" and try again.

**Comment by btetz14** [comment]
arm-none-eabi-gcc
   https://developer.arm.com/tools-and-software/open-source-software/developer-tools/gnu-toolchain/gnu-rm/downloads
   Download "gcc-arm-none-eabi-9-2019-q4-major-win32.exe"
   Install it
   There should be a User Variable "path" to "C:\Program Files (x86)\GNU Tools Arm Embedded\9 2019-q4-major\bin", if not add it

**Comment by btetz14** [comment]
JLinkExe
   https://www.segger.com/downloads/jlink/#J-LinkSoftwareAndDocumentationPack
   J-Link Software and Documentation pack for Windows
   Download JLink_Windows_V662d.exe
   Install it
   It installs to "C:\Program Files (x86)\SEGGER\JLink" so add that path to your path variable
   Create a symbolic link to Jlink.exe:
       open up a new cmd window and cd to the JLink folder
       run this command "mklink JLinkExe.exe JFlash.exe"
   Now the "make flash" command will work.

**Comment by ppannuto** [comment]
I don't really understand why this change should be necessary, using order-only rules to make a build directory like this is the exact use case as described in the make manual: https://www.gnu.org/software/make/manual/make.html#Prerequisite-Types

One thing that caught my eye from your install directions was:
>  Install make-3.81.exe

I had to look it up, but make version 3.81 was released in 2006. It's a bit hard to find, but it looks like support for order-only rules was added in make version 3.80, so it's quite likely that there is bug in that very old version of make that's actually at issue here.

Can you try updating your make to at least something in the 4.0 family (released in 2013) and see if this is still/actually a problem?

**Pull request closed without merging**
